package autoattendance;

import static java.lang.Compiler.disable;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author imn99
 */
public class StudentInfo extends javax.swing.JFrame {

    /**
     * Creates new form StudentInfo
     */
    public StudentInfo() {
        initComponents();
        
         loadData();
        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        addStudentBtn = new javax.swing.JButton();
        deleteStudentBtn = new javax.swing.JButton();
        updateStudentBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        importStdButton = new javax.swing.JButton();
        studentInfoCourseComboBox1 = new javax.swing.JComboBox();
        studentInfoSectionComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        studentSearchjButton1 = new javax.swing.JButton();
        stduentPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stdInfoTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Section:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Course:");

        IDTextField.setBackground(studentPanel1.getBackground());
        IDTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDTextField.setForeground(new java.awt.Color(255, 255, 255));
        IDTextField.setBorder(null);
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        lastNameTextField.setBackground(studentPanel1.getBackground());
        lastNameTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setBorder(null);

        firstNameTextField.setBackground(studentPanel1.getBackground());
        firstNameTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setBorder(null);

        addStudentBtn.setBackground(studentPanel1.getBackground());
        addStudentBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addStudentBtn.setForeground(new java.awt.Color(255, 255, 255));
        addStudentBtn.setText("Add");
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });

        deleteStudentBtn.setBackground(studentPanel1.getBackground());
        deleteStudentBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteStudentBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteStudentBtn.setText("Delete");
        deleteStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentBtnActionPerformed(evt);
            }
        });

        updateStudentBtn.setBackground(studentPanel1.getBackground());
        updateStudentBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateStudentBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateStudentBtn.setText("Update");
        updateStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Student Infomration");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));

        importStdButton.setBackground(studentPanel1.getBackground());
        importStdButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        importStdButton.setForeground(new java.awt.Color(255, 255, 255));
        importStdButton.setText("Import");

        studentInfoCourseComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        studentInfoCourseComboBox1.setBorder(studentInfoSectionComboBox1.getBorder());
        studentInfoCourseComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoCourseComboBox1ActionPerformed(evt);
            }
        });

        studentInfoSectionComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\imn99\\Downloads\\Go Back_35px.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        studentSearchjButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studentSearchjButton1.setText("Search");
        studentSearchjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPanel1Layout = new javax.swing.GroupLayout(studentPanel1);
        studentPanel1.setLayout(studentPanel1Layout);
        studentPanel1Layout.setHorizontalGroup(
            studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanel1Layout.createSequentialGroup()
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(addStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(updateStudentBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importStdButton)
                        .addGap(67, 67, 67))
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studentPanel1Layout.createSequentialGroup()
                                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel7)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(studentPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4))
                                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(studentPanel1Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(studentInfoCourseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(studentInfoSectionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(studentPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentPanel1Layout.createSequentialGroup()
                                                        .addGap(28, 28, 28)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jSeparator3)
                                                            .addComponent(firstNameTextField)))
                                                    .addGroup(studentPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                .addGap(35, 35, 35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentSearchjButton1)
                    .addComponent(deleteStudentBtn))
                .addGap(56, 56, 56))
        );
        studentPanel1Layout.setVerticalGroup(
            studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanel1Layout.createSequentialGroup()
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentSearchjButton1)
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studentPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addGap(105, 105, 105)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(studentInfoCourseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(studentInfoSectionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importStdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        stduentPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\imn99\\Downloads\\Delete_35px.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout stduentPanel2Layout = new javax.swing.GroupLayout(stduentPanel2);
        stduentPanel2.setLayout(stduentPanel2Layout);
        stduentPanel2Layout.setHorizontalGroup(
            stduentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stduentPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        stduentPanel2Layout.setVerticalGroup(
            stduentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stduentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        stdInfoTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stdInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Last Name", "First Name", "Course", "Section"
            }
        ));
        stdInfoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stdInfoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stdInfoTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(studentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stduentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(stduentPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1282, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed

       int cid = 0;

        DatabaseConnection dbConnection = new DatabaseConnection();

        String studentId = IDTextField.getText();
        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String courseName = studentInfoCourseComboBox1.getSelectedItem().toString();
        String section = studentInfoSectionComboBox1.getSelectedItem().toString();

        try {
            Connection con = dbConnection.createConnection();
            Statement st = con.createStatement();
            ResultSet rs2 = st.executeQuery("SELECT * FROM `students` where `students`.`Student_Id` = '" + studentId + "'");
            if (!rs2.next()) {
                Statement st1 = con.createStatement();
                st1.executeUpdate("INSERT INTO `students` (`Student_Id`, `First_Name`, `Last_Name`)  VALUES ('" + studentId + "','" + lastName + "','" + firstName + "');");
                ResultSet rs1 = st1.executeQuery("SELECT * FROM `course` where `course`.`Course_Name` = \'" + courseName + "\' and `course`.`Section` = \'" + section + "\' ");

                if (rs1.next()) {
                    cid = rs1.getInt("id");
                }

                Statement st2 = con.createStatement();
                st2.executeUpdate("INSERT INTO `studentcourse` (`CID`, `SID`)  VALUES ('" + cid + "','" + studentId + "');");
                JOptionPane.showMessageDialog(null, "Student's information added");
            } else {

                ResultSet rs1 = st.executeQuery("SELECT * FROM `course` where `course`.`Course_Name` = \'" + courseName + "\' and `course`.`Section` = \'" + section + "\' ");

                if (rs1.next()) {
                    cid = rs1.getInt("id");
                }
                Statement st2 = con.createStatement();
                ResultSet rs3 = st2.executeQuery("SELECT * FROM `studentcourse` where `studentcourse`.`SID` ='" + studentId + "' and `studentcourse`.`CID` = " + cid + " ");
                if (rs3.next()) {
                    JOptionPane.showMessageDialog(null, " Cannnot add.Student is already enlisted on that course");
                } else {
                    Statement st3 = con.createStatement();
                    st3.executeUpdate("INSERT INTO `studentcourse` (`CID`, `SID`)  VALUES ('" + cid + "','" + studentId + "');");
                    JOptionPane.showMessageDialog(null, "Student's information added");
                }
            }
    
        } catch (Exception ex) {
            System.out.println(ex);
            ex.printStackTrace();
        }

        loadData();
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void deleteStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentBtnActionPerformed

      deleteInfo();
        loadData();
    }//GEN-LAST:event_deleteStudentBtnActionPerformed

    private void updateStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentBtnActionPerformed

       updateInfo(IDTextField.getText(), firstNameTextField.getText(), lastNameTextField.getText(), studentInfoCourseComboBox1.getSelectedItem().toString(), studentInfoSectionComboBox1.getSelectedItem().toString());
        loadData();
    }//GEN-LAST:event_updateStudentBtnActionPerformed

    private void studentInfoCourseComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentInfoCourseComboBox1ActionPerformed
        // TODO add your handling code here:
        
                                                                    
        try {
            // TODO add your handling code here:
            studentInfoSectionComboBox1.removeAllItems();
            String courseName = "";
            DatabaseConnection dbConnection = new DatabaseConnection();
            Connection con = dbConnection.createConnection();

            String sql = "Select * From course";
            Statement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            String courseName2 = studentInfoCourseComboBox1.getSelectedItem().toString();
            ResultSet rs1 = st.executeQuery("SELECT section FROM `course` where `course`.`Course_Name` = \'" + courseName2 + "\'");

            while (rs1.next()) {

                String section = rs1.getString("Section");
                studentInfoSectionComboBox1.addItem(section);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
    }//GEN-LAST:event_studentInfoCourseComboBox1ActionPerformed

    private void stdInfoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdInfoTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stdInfoTableMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         new Panel1().setVisible(true);
         dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void studentSearchjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchjButton1ActionPerformed
        // TODO add your handling code here:
        try {
//            if(IDTextField.equals(true))
//            {
            DatabaseConnection dbConnection = new DatabaseConnection();
            Connection con = dbConnection.createConnection();
            search(IDTextField.getText());
         //   }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "Not FOund");
//            }

        } catch (Exception e) {
            System.out.println(e);

        }
    }//GEN-LAST:event_studentSearchjButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

      void loadData() {

        try {

            DatabaseConnection dbConnection = new DatabaseConnection();
            Connection con = dbConnection.createConnection();

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select `students`.`Student_Id`,`students`.`Last_Name`,`students`.`First_Name`,`course`.`Course_Name`,`course`.`Section` from `students` ,`course`,`studentcourse` Where `students`.`Student_Id`=`studentcourse`.`SID` and `course`.`id`=`studentcourse`.`CID`");
            
            
            while (stdInfoTable.getRowCount() > 0) {

                ((DefaultTableModel) stdInfoTable.getModel()).removeRow(0);

            }

            int col = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {
                    rows[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) stdInfoTable.getModel()).insertRow(rs.getRow() - 1, rows);

            }
            rs.close();
            st.close();

        } catch (Exception ex) {

        }
    }

    void loadComboBox() {

        try {

            String courseName = "";
            DatabaseConnection dbConnection = new DatabaseConnection();
            Connection con = dbConnection.createConnection();

            HashSet<String> course = new HashSet<String>();

            String sql = "Select * From course";
            Statement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                courseName = rs.getString("Course_Name");
                course.add(courseName);

            }

            for (String s : course) {
                studentInfoCourseComboBox1.addItem(s);

            }
            String courseName2 = studentInfoCourseComboBox1.getSelectedItem().toString();
            ResultSet rs1 = st.executeQuery("SELECT section FROM `course` where `course`.`Course_Name` = \'" + courseName2 + "\'");

            while (rs1.next()) {

                String section = rs1.getString("Section");
                studentInfoSectionComboBox1.addItem(section);
            }

        } catch (Exception ex) {

        }

    }

    public void search(String searchID) {
        DatabaseConnection dbConnection = new DatabaseConnection();
        int cid = 0;
        ResultSet rs = null;
        ResultSet rs2 = null;
        ResultSet rs3 = null;

        try {
            Connection con = dbConnection.createConnection();
            Statement st = con.createStatement();

            String query = "select * from `students` WHERE `students`.`Student_Id` = \'" + searchID + "\';";
            String query1 = "select * from `studentcourse` WHERE `studentcourse`.`SID` ='" + searchID + "'";
            System.out.println(query);
            rs = st.executeQuery(query);

            Statement st2 = con.createStatement();
            rs2 = st2.executeQuery(query1);
            if (rs2.next()) {
                cid = rs2.getInt("CID");
            }
            // search(IDTextField.getText());
            Statement st3 = con.createStatement();
            rs3 = st3.executeQuery("SELECT * FROM `course` where `course`.`id` =" + cid + " ");
            firstNameTextField.setText("");
            lastNameTextField.setText("");
            studentInfoCourseComboBox1.addItem("");
            studentInfoSectionComboBox1.addItem("");
            while (rs.next()) {

                lastNameTextField.setText(rs.getString("First_Name"));
                firstNameTextField.setText(rs.getString("Last_Name"));

            }
            while (rs3.next()) {
                String courseName = rs3.getString("Course_Name");

                studentInfoCourseComboBox1.setSelectedItem(courseName);
                String section = rs3.getString("Section");

                studentInfoSectionComboBox1.setSelectedItem(section);
            }

        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();;
        }

    }

    public void updateInfo(String searchID, String fn, String ln, String course, String section) {
        try {
            DatabaseConnection dbConnection = new DatabaseConnection();
            Connection con = dbConnection.createConnection();
            int cid = 0;

            Statement st = con.createStatement();
            Statement st1 = con.createStatement();
            Statement st2 = con.createStatement();

            String query = "Update `students` set `students`.`First_Name` = \'" + ln + "\',`students`.`Last_Name` = \'" + fn + "\' where `students`.`Student_ID`=\'" + searchID + "\'";
            st.executeUpdate(query);

            ResultSet rs1 = st1.executeQuery("SELECT * FROM `studentcourse` where `studentcourse`.`SID` = \'" + searchID + "\'");

            if (rs1.next()) {
                cid = rs1.getInt("CID");
            }
            String query2 = "Update `course` set `course`.`Course_Name` = \'" + course + "\',`course`.`Section` = \'" + section + "\'  where `course`.`id`=" + cid + "";

            st2.executeUpdate(query2);

            JOptionPane.showMessageDialog(null, "Student info updated successfully !!");
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void deleteInfo() {
        DatabaseConnection dbConnection = new DatabaseConnection();
        int cid=0;
        String studentId = IDTextField.getText();
        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String courseName = studentInfoCourseComboBox1.getSelectedItem().toString();
        String section = studentInfoSectionComboBox1.getSelectedItem().toString();
        try {
            Connection con = dbConnection.createConnection();
            Statement st = con.createStatement();
            Statement st1 = con.createStatement();
            st.executeUpdate("DELETE FROM `students` WHERE `students`.`Student_Id` = \'" + studentId + "\' and`students`.`First_Name` = \'" + lastName + "\' and `students`.`Last_Name` = \'" + firstName + "\' ");
            ResultSet rs1 = st1.executeQuery("SELECT * FROM `course` where course`.`Course_Name` = \'" + courseName + "\',`course`.`Section` = \'" + section + "'");

            if (rs1.next()) {
                cid = rs1.getInt("id");
            }
           st1.executeUpdate("DELETE FROM `studentcourse` WHERE `studentcourse`.`Student_Id` = \'" + studentId + "\' and`studentcourse`.`CID` =" + cid + "");
            
            JOptionPane.showMessageDialog(null, "Student's information deleted successfully !!");

        } catch (Exception ex) {

            System.out.println(ex);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JButton deleteStudentBtn;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton importStdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTable stdInfoTable;
    private javax.swing.JPanel stduentPanel2;
    private javax.swing.JComboBox studentInfoCourseComboBox1;
    private javax.swing.JComboBox studentInfoSectionComboBox1;
    private javax.swing.JPanel studentPanel1;
    private javax.swing.JButton studentSearchjButton1;
    private javax.swing.JButton updateStudentBtn;
    // End of variables declaration//GEN-END:variables
}
